# -*- coding: utf-8 -*-
"""Lection4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UWugCtgWVup-7Uq7Pc5mAwCcsiQcfyN-
"""

# 01. Операции с числами. Задача 1. 
radius = 36
import math
S = math.pi * radius ** 2.0
print('S = ', round(S, 4))

# 05. Операции со списками. Задача 1.
shop_list = ['Картофель', 'Горошек', 'Рис', 'Хлеб']
shop_list.insert(2, 'Рыба')
print('a.', shop_list)
fruits = ['Яблоко', 'Апельсин', 'Клубника']
shop_list += fruits
print('b.', shop_list)
shop_list.remove('Картофель')
print('c.', shop_list)
bread = shop_list.index('Хлеб')
orange = shop_list.index('Апельсин')
print('d. Элемент "Хлеб" имеет номер', bread, '\n элемент "Апельсин" имеет номер', orange)